# site settings
title: Michaela Brankova
subtitle: Portfolio
email: mi.brankova@gmail.com
description: Here is a collection of some of my recent data projects.
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "https://mihaelabr.github.io" # the base hostname & protocol for your site
author: Michaela Brankova
city: Zürich
country: Switzerland
rights: All content rights reserved

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/mihaelabr
  LinkedIn: https://www.linkedin.com/in/michaela-brankova
  Kaggle: https://www.kaggle.com/michaelabrankova
  Salesforce: https://public.tableau.com/app/profile/mihaela.brankova5845/vizzes

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
